### ISSUE TITLE
Large mp3

### ISSUE THREAD

**Issue by BluGeni** [schollz/musicsaur#12]
This might not be a super big deal or worth looking at but I noticed that if you use a super large mp3 it will "crash" the chrome tab saying something went wrong and it disconnects from the server.

**Comment by timelf123** [comment]
How big was the file?

**Comment by BluGeni** [comment]
137,956 KB (it is a ton of songs in one file) so it may not be worth looking into just wanted to let anyone know that is having that issue.

**Comment by schollz** [comment]
This bug confirmed, tested using a 148MB file and Chrome 47. The error is "Inspected target disconnected" and it seems that is because the instance of Chrome has memory issues (plenty of RAM though).

Interestingly, the same file works just fine on a Raspberry Pi B running Midori!

**Comment by schollz** [comment]
So I've also noticed that Raspberry Pis have an especially hard time with larger 5MB are so. They can't seem to seek very far or very quickly. One way around this is using ffmpeg which I will add is as an option to fix this (issue #24). I don't know if there's a better way to do big files, other than piping which I'd like to save for later.
