### ISSUE TITLE
Porting to Golang (for simpler cross-platform deployment)

### ISSUE THREAD

**Issue by schollz** [schollz/musicsaur#29]
The serverside stuff is very simple and should be relatively easy to write in Golang. Possibly for v2.0.

One thing I don't know how to port is the Python Threading.timer(). Any ideas would be appreciated!

**Comment by blakev** [comment]
Why would you want to port it to Golang? Python is perfectly capable.

**Comment by schollz** [comment]
It certainly is! 

I am interested in porting it so it can be compiled and run as an executable without any dependencies. This would useful for the non-tech savvy folks that just want to download, unzip, and run, or if you don't want to have a Python installation on the server computer. Also, selfishly, I'm interesting in porting because I love learning Go and don't really have a clue how to do some things that I can do in Python (like the Threading timer).

**Comment by blakev** [comment]
So....should we not clean this one up if it's just going to get rewritten? :P

**Comment by schollz** [comment]
I'd really appreciate the help cleaning it up. I'm still learning Python too, so it'd be nice to know what I'm doing wrong in terms of writing clean code.

Also, I expect not to port for quite awhile. I dug around some more and found that Go is currently lacking in MP3 parsing (though [I figured out how to do timers, its easy!](https://play.golang.org/p/rriapR5fzv)) and I'm not apt to writing one myself...

**Comment by schollz** [comment]
I got it in the works: https://github.com/schollz/musicsaur/tree/1.3/go

**Comment by schollz** [comment]
Add in version 1.3
