### ISSUE TITLE
Broken config file in master branch

### ISSUE THREAD

**Issue by Loki-Afro** [schollz/musicsaur#37]
https://github.com/schollz/musicsaur/blob/master/config-python.cfg seems to be broken, like a faulty merge. See Line 26 for example.

Due to this issue the referenced line 42 in Readme.md is not where it should be. Maybe there are more issues related to this.

**Comment by schollz** [comment]
Sorry about that, it should be fixed now.

**Comment by Loki-Afro** [comment]
Looks good now :)
