### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by BluGeni** [schollz/musicsaur#41]
When i run go get./... I get this error :

:~/musicsaur$ go get ./...
package github.com/BurntSushi/toml: cannot download, $GOPATH not set. For more details see: go help gopath
package github.com/bobertlo/go-id3/id3: cannot download, $GOPATH not set. For more details see: go help gopath
package github.com/mholt/caddy/caddy: cannot download, $GOPATH not set. For more details see: go help gopath
package github.com/tcolgate/mp3: cannot download, $GOPATH not set. For more details see: go help gopath
Segmentation fault (core dumped)

**Comment by schollz** [comment]
You need to set your `GOPATH`. Make a folder somewhere to store the dependencies (e.g. `mkdir $HOME/work`) and then set the path with `export GOPATH=$HOME/work`. More info [here](https://golang.org/doc/install#testing).
